name: spec_mirror-ci

on:
  push:
    branches: [master]
  pull_request:
    branches: "*"

jobs:
  check_format:
    strategy:
      fail-fast: false
      matrix:
        shard_file:
          - shard.yml
        crystal_version:
          - 1.0.0
          - 1.1.0
        experimental:
          - false
        include:
          - shard_file: shard.edge.yml
            crystal_version: 1.1.0
            experimental: true
          - shard_file: shard.yml
            crystal_version: nightly
            experimental: true
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    steps:
      - uses: actions/checkout@v1
      - uses: crystal-lang/install-crystal@v1
        with:
          crystal: ${{matrix.crystal_version}}
      - name: Install shards
        run: SHARDS_OVERRIDE=${{ matrix.shard_file }} shards install
      - name: Format
        run: crystal tool format --check
      - name: Lint
        run: ./bin/ameba
